scypher:
  function_name: [ "now", "timePoint", "interval", "interval.intersection", "interval.range", "interval.difference", "during", "overlaps", "cPath", "pairCPath", "earliestSPath", "latestSPath", "fastestSPath", "shortestSPath" ]
  procedure_name: [ ]

graph_database:
  out_net_ip: "118.25.15.14"
  out_net_port: 1111
  host_user: "jtt"
  host_password: "123456"
  database_ip: "0.0.0.0"
  database_port: 7687
  database_user: "neo4j"
  database_password: "s-cypher"